Unbreak PyThemis installation on CircleCI
CircleCI builds for "release/0.13" and "stable" are still using
"cossacklabs/android-build:2019.01" images based on Ubuntu 16.04.
The version of "python3-setuptools" there is old enough to be not
compatible with PyPI repository format, which results in PyThemis
installation failing with the following errors:

    Processing dependencies for pythemis==0.13.0
    Searching for six
    Reading https://pypi.python.org/simple/six/
    Couldn't find index page for 'six' (maybe misspelled?)
    Scanning index of all packages (this may take a while)
    Reading https://pypi.python.org/simple/
    No local packages or download links found for six
    error: Could not find suitable distribution for Requirement.parse('six')
    Makefile:599: recipe for target 'pythemis_install' failed
    make: *** [pythemis_install] Error 1

Ideally, we should migrate away from setup.py to a "modern" toolchain
-- whatever that is right now in pythonland -- but that's a story for
another day. Definitely not for the stable branch. Installing "six"
with "pip3" works even with Ubuntu 16.04 versions of Python toolchain.

Other CircleCI jobs use "cossacklabs/build:ubuntu-bionic" image which
lacks some things preinstalled in "cossacklabs/android-build:2019.01"
(such as Go toolchain).

I don't really have neither time nor desire to fiddle with these old
images, rebuilding them properly, etc. However, I do desire to not
see maintainers ignoring red builds like it's everyday occurence.
Therefore, here is my compromise: these build images are turned into
chimeric abominations of Ubuntu 16.04 + 18.04 repositories, just to
pull in a newer version of "python3-setuptools" which is able to
install PyThemis dependencies and allow the build to proceed.