pythemis: Handle 'library not found' errors more nicely
Turns out, if find_library() cannot find a library it simply returns
None and then LoadLibrary() does not raise an exception for that,
instead loading a "None" library, lol. That won't do.

We had people run into situations where native library could not be
found and then the interpreter reports errors like

    AttributeError: dlsym(RTLD_DEFAULT, themis_gen_sym_key): symbol not found

which confusingly *look like* some issues with library symbols.