Fix warnings from Clippy
Recently released Rust 1.51 includes new Clippy with new warnings:

    error: name `GetPublicKeyForID` contains a capitalized acronym
       --> src/wrappers/themis/rust/tests/secure_session.rs:663:6
        |
    663 | type GetPublicKeyForID = Box<dyn FnMut(&[u8]) -> Option<EcdsaPublicKey>>;
        |      ^^^^^^^^^^^^^^^^^ help: consider making the acronym lowercase, except the initial letter: `GetPublicKeyForId`
        |
        = note: `-D clippy::upper-case-acronyms` implied by `-D warnings`
        = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms

    error: aborting due to previous error

Shut up, Clippy, I name my types however I want to!^K

I mean, yes, sure, O Wise Stationery, I will immediately rename the
entity as prescribed and will refrain from such practice any further.

(cherry picked from commit 734a62433aa82c9f626cc8ca159fba412d85e399)