Use correct Javadoc syntax for @param
While tinkering with publishing of AndroidThemis I have found out that
Javadoc generator yells at me with a ton of errors like

    src/wrappers/themis/java/com/cossacklabs/themis/KeypairGenerator.java:49: error: @param name not found
             * @param key type (EC or RSA)

    [...]

    src/wrappers/themis/java/com/cossacklabs/themis/SecureSession.java:38: error: malformed HTML
                    NEGOTIATING, /** < key agreement is in progress. No data exchange possible yet. */
                                     ^
    36 errors
    36 warnings

    > Task :android:generateJavadoc FAILED

when I do

    ./gradlew :android:generateJavadoc

which is a part of publication process.

Well, this won't fly for proper publication so let's fix it. At least,
make the Javadoc generator happy at first.

Make sure that all @param lines have an actual parameter name followed
by its description. I make no effort to make it "good", only making it
correct. Improving quality of API documentation -- ideally across all
wrappers -- is a project for another day.