Break error message lines for readability
Error messages don't show nicely because they are a bit too long. Make
sure they are formatted like this:

   Error: Themis: SecureCellContextImprint:
   context must be not empty

which looks a bit better. The "source" of the error on one line, and
its "body" on the following one.